### PR TITLE
Feature/containerize

### PR DESCRIPTION
**Pull request by niklas-sparfeld**
Drei Themen werden hier bearbeitet:

1. Build releases mit Distillery: https://hexdocs.pm/distillery/guides/phoenix_walkthrough.html
2. Deployment mit Docker: https://hexdocs.pm/distillery/guides/working_with_docker.html
3. Migrations in prod: https://hexdocs.pm/distillery/guides/running_migrations.html

Ich habe es nun doch geschafft, dass das auch in docker-compose läuft. Damit geht ein kleiner breaking change einher: Man muss explizit angeben, dass man nur die DB starten will, wenn man lokal per `mix phx.server` entwickelt: `docker-compose up -d db`.

### CODE REVIEW

**Review by Screamer2087 — COMMENTED** [review]
Hm, also wenn ich mit `docker-compose build && docker-compose up` versuche das zu starten, scheint da erst einmal nicht zu klappen:

db_1       | 2019-03-04 11:21:35.220 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2019-03-04 11:21:35.221 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2019-03-04 11:21:35.224 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2019-03-04 11:21:35.235 UTC [18] LOG:  database system was shut down at 2019-03-04 11:21:33 UTC
backend_1  | DATABASE_USER=postgres
backend_1  | HOSTNAME=localhost
backend_1  | SHLVL=1
backend_1  | PORT=4000
backend_1  | HOME=/root
backend_1  | DATABASE_NAME=simplefootball_web_prod
backend_1  | APP_NAME=simplefootball_web
backend_1  | ERLANG_COOKIE=simplefootball
backend_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
backend_1  | LANG=en_US.UTF-8
backend_1  | SECRET_KEY_BASE=u1QXlca4XEZKb1o3HL/aUlznI1qstCNAQ6yme/lFbFIs0Iqiq/annZ+Ty8JyUCDc
backend_1  | DATABASE_PASS=postgres
backend_1  | REPLACE_OS_VARS=false
backend_1  | PWD=/opt/app
backend_1  | DATABASE_HOST=db
backend_1  | Preparing to run migrations
db_1       | 2019-03-04 11:21:35.239 UTC [1] LOG:  database system is ready to accept connections
db_1       | 2019-03-04 11:21:39.662 UTC [25] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.664 UTC [26] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.666 UTC [27] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.672 UTC [28] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.672 UTC [30] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.675 UTC [32] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.675 UTC [29] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.676 UTC [33] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:39.678 UTC [31] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.650 [info] Running SimplefootballWebWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000
backend_1  | 11:21:39.672 [error] Postgrex.Protocol (#PID<0.1535.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.672 [error] Postgrex.Protocol (#PID<0.1534.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.672 [error] Postgrex.Protocol (#PID<0.1533.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.684 [error] Postgrex.Protocol (#PID<0.1532.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.684 [error] Postgrex.Protocol (#PID<0.1530.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.684 [error] Postgrex.Protocol (#PID<0.1524.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.686 [error] Postgrex.Protocol (#PID<0.1531.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.686 [error] Postgrex.Protocol (#PID<0.1529.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.686 [error] Postgrex.Protocol (#PID<0.1525.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:39.687 [error] Postgrex.Protocol (#PID<0.1528.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | pong
backend_1  | Application is up!
db_1       | 2019-03-04 11:21:39.681 UTC [34] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | Running migrations
db_1       | 2019-03-04 11:21:40.716 UTC [35] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:40.717 [error] Postgrex.Protocol (#PID<0.1533.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:41.137 UTC [36] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:41.138 [error] Postgrex.Protocol (#PID<0.1531.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:41.172 UTC [37] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:41.173 [error] Postgrex.Protocol (#PID<0.1528.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:41.451 UTC [38] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:41.453 [error] Postgrex.Protocol (#PID<0.1530.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.004 UTC [39] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.006 [error] Postgrex.Protocol (#PID<0.1535.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.063 UTC [40] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.064 [error] Postgrex.Protocol (#PID<0.1534.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.076 UTC [41] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.077 [error] Postgrex.Protocol (#PID<0.1524.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.107 UTC [42] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.109 [error] Postgrex.Protocol (#PID<0.1525.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.453 UTC [43] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.454 [error] Postgrex.Protocol (#PID<0.1529.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.514 UTC [44] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.515 [error] Postgrex.Protocol (#PID<0.1533.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.560 [error] Postgrex.Protocol (#PID<0.1532.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | Starting dependencies..
backend_1  | Starting repos..
db_1       | 2019-03-04 11:21:42.559 UTC [45] FATAL:  database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.819 UTC [47] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | Running migrations for simplefootball_web
backend_1  | 11:21:42.840 [error] Postgrex.Protocol (#PID<0.145.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:42.820 UTC [46] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:42.840 [error] Postgrex.Protocol (#PID<0.146.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:43.179 UTC [48] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:43.180 [error] Postgrex.Protocol (#PID<0.1528.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:43.773 UTC [49] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:43.774 [error] Postgrex.Protocol (#PID<0.1531.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:44.416 UTC [50] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:44.417 [error] Postgrex.Protocol (#PID<0.1530.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:44.489 UTC [51] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:44.489 [error] Postgrex.Protocol (#PID<0.146.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:45.079 UTC [52] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:45.081 [error] Postgrex.Protocol (#PID<0.145.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:45.532 [error] Postgrex.Protocol (#PID<0.1533.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
backend_1  | 11:21:45.775 [error] Could not create schema migrations table. This error usually happens due to the following:
backend_1  |
backend_1  |   * The database does not exist
backend_1  |   * The "schema_migrations" table, which Ecto uses for managing
backend_1  |     migrations, was defined by another library
backend_1  |
backend_1  | To fix the first issue, run "mix ecto.create".
backend_1  |
backend_1  | To address the second, you can run "mix ecto.drop" followed by
backend_1  | "mix ecto.create". Alternatively you may configure Ecto to use
backend_1  | another table for managing migrations:
backend_1  |
backend_1  |     config :simplefootball_web, SimplefootballWeb.Repo,
backend_1  |       migration_source: "some_other_table_for_schema_migrations"
backend_1  |
backend_1  | The full error report is shown below.
backend_1  |
db_1       | 2019-03-04 11:21:45.531 UTC [53] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | ▸  Evaluation failed with: connection not available and request was dropped from queue after 2953ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
backend_1  | ▸      (ecto_sql) lib/ecto/adapters/sql.ex:624: Ecto.Adapters.SQL.raise_sql_call_error/1
backend_1  | ▸      (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
backend_1  | ▸      (ecto_sql) lib/ecto/adapters/sql.ex:711: Ecto.Adapters.SQL.execute_ddl/4
backend_1  | ▸      (ecto_sql) lib/ecto/migrator.ex:493: Ecto.Migrator.verbose_schema_migration/3
backend_1  | ▸      (ecto_sql) lib/ecto/migrator.ex:269: Ecto.Migrator.run/4
backend_1  | ▸      (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
backend_1  | ▸      (elixir) lib/enum.ex:769: Enum.each/2
backend_1  | ▸      (simplefootball_web) lib/release_tasks.ex:16: SimplefootballWeb.ReleaseTasks.migrate/1
db_1       | 2019-03-04 11:21:46.430 UTC [54] FATAL:  database "simplefootball_web_prod" does not exist
backend_1  | 11:21:46.431 [error] Postgrex.Protocol (#PID<0.1525.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "simplefootball_web_prod" does not exist
db_1       | 2019-03-04 11:21:46.828 UTC [55] FATAL:  database "simplefootball_web_prod" does not exist

**Comment by niklas-sparfeld** [comment]
Ist korrekt: Die prod umgebung geht davon aus, dass die DB bereits existiert. Sprich: Migrate wird ausgeführt, aber es gibt kein `ecto.create`-Äquivalent.

Das ist auch gewollt, weil viele managed Datenbanken (e.g. auf Azure) haben bereits eine Datenbank.

**Comment by Screamer2087** [comment]
Okay. Heißt das, dass die compose nicht für den lokalen Einsatz geeignet ist oder falls doch, wie muss ich sie benutzen?

**Comment by niklas-sparfeld** [comment]
Ich benutze Postico und habe darin die Datenbank leer angelegt.

https://eggerapps.at/postico/

**Comment by niklas-sparfeld** [comment]
Und ja: Das compose ist wirklich eher dafür da, dass man das prod docker image lokal gut testen kann. Nicht so richtig zur Entwicklung. Auch ist es so zugegebenermaßen ziemlich ungeeignet, um neue Leute zu onboarden.

"Hier ist ein einziger command. du brauchst nur den auszuführen." ... "außer natürlich dass du vorher noch die DB aufsetzen musst..."

**Comment by Screamer2087** [comment]
Okay, also wäre der Workflow, wenn man noch nix hat: 
- docker-compose build und up
- Mit einem PostgeSQL-Client die entsprechende Datenbank anlegen
- docker-compose up noch einmal ausführen
?

**Comment by niklas-sparfeld** [comment]
Das wäre wohl so, ja.

Aber wie gesagt: Das ist eigentlich nur dann nötig, wenn man überhaupt docker-compose nutzen will.

Ich würde sage, dass lokal by default eher mit `mix phx.server` gearbeitet werden sollte.

Also dann wenn man noch nix hat:

* Installiere dependencies
* Setze das Phoenix project auf
* Starte postgres via docker-compose
* Entwickle mit mix phx.server

**Comment by Screamer2087** [comment]
Ja kommt ein wenig drauf an aus meiner Sicht ob man nun am Backend rumschraubt - dann auf jeden Fall - oder am Frontend, dann vielleicht eher weniger. Aber passt schon.

**Review by Screamer2087 — APPROVED** [review]

**Pull request merged**
